#!/usr/bin/env bash
#
# Build

set -ex -o pipefail

source docker.sh

command_build() {
  docker::build . 'base'
}

command_push() {
  docker::push 'base'
}

main() {
  "command_${1:-build}" "${@:2}"
}

main "$@"
