#!/usr/bin/env bash
#
# Install img

set -e -o pipefail

: ${IMG_VERSION:='0.5.1'}
: ${IMG_SHA1SUM:='c4f948c7fb639366432ac8816ec3f72cecc7f9b7'}

: ${PREFIX:=/usr/local}
: ${BINDIR:="${PREFIX}/bin"}

if [[ "${PREFIX:0:1}" != '/' ]]; then
  echo "$(basename $0): PREFIX must be an absolute path" >&2
  exit 1
fi

if [[ "${BINDIR:0:1}" != '/' ]]; then
  echo "$(basename $0): BINDIR must be an absolute path" >&2
  exit 1
fi

if [[ -n "$(which sha1sum)" ]]; then
  sha1_prog='sha1sum -c'
elif [[ -n "$(which shasum)" ]]; then
  sha1_prog='shasum -a 1 -c'
else
  echo "$(basename $0): No sha1 program found" >&2
  exit 1
fi

mkdir -p "${BINDIR}"
wget "https://github.com/genuinetools/img/releases/download/v${IMG_VERSION}/img-linux-amd64" \
  -nv -O "${BINDIR}/img"
trap "rm ${BINDIR}/img" ERR
${sha1_prog} <<< "${IMG_SHA1SUM}  ${BINDIR}/img"
chmod +x "${BINDIR}/img"
