#!/usr/bin/env bash
#
# Docker convenience wrapper

set -e -o pipefail

: ${REGISTRY_USER:="$(id -un)"}
: ${REGISTRY:="registry-1.docker.io/${REGISTRY_USER}"}
: ${TAG:='master'}

: ${CACHE_TAGS:='master latest'}

command_build() {
  local cache_from
  local context="${1?Context must be specified}"
  local name="${2?Name must be specified}"
  local repository="${REGISTRY}/${name}"
  for cache_tag in "${TAG}" ${CACHE_TAGS}; do
    if [[ -z "$(docker image ls -q ${repository}:${cache_tag})" ]]; then
      docker image pull "${repository}:${cache_tag}" || true
    fi
    cache_from="--cache-from ${repository}:${cache_tag} ${cache_from}"
  done
  docker image build \
    --build-arg REGISTRY="${REGISTRY}" \
    --build-arg TAG="${TAG}" \
    ${cache_from} \
    -t "${repository}:${TAG}" "${context}"
}

command_push() {
  local name="${1?Name must be specified}"
  if [[ -z "${is_logged_in}" ]]; then
    trap "docker logout ${REGISTRY?Registry must be specified}" EXIT
    docker login --password-stdin -u "${REGISTRY_USER}" "${REGISTRY}"
    is_logged_in=1
  fi
  docker image push "${REGISTRY}/${name}:${TAG}"
}

main() {
  "command_${1?Command must be specified}" "${@:2}"
}

main "$@"
