#!/usr/bin/env bash
#
# Makes a list of files and links with ckecksums for a directory content

# Arguments:
#   1: Directory
# Outputs:
#   STDOUT: An ordered list of files and links with checksums

set -e -o pipefail

find "${1?}" -type f -o -type l | xargs -I {} cksum {} | sort
