#!/usr/bin/env bash
#
# Makes a list of files and links with ckecksums for a directory
# content and saves them under a specified name

# Arguments:
#   1: Name
#   2: Directory

set -e -o pipefail

mkdir -p /var/tmp/checksum

find "${2?}" -type f -o -type l \
  | xargs -I {} cksum {} \
  | sort > "/var/tmp/checksum/${1?}.crc"
