#!/usr/bin/env bash
#
# Compares two names checksum lists made by `checksum_dir` and removes
# unchanged files and links

# Arguments:
#   1: Name 1
#   2: Name 2

set -e -o pipefail

comm -1 -2 "/var/tmp/checksum/${1?}.crc" "/var/tmp/checksum/${2?}.crc" \
  | cut -d ' ' -f 3 \
  | xargs -I {} rm {}
